name: myapp
description: A exported flutter project from FUNCTION12


# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number is used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
# In Windows, build-name is used as the major, minor, and patch parts
# of the product and file versions while build-number is used as the build suffix.
version: 1.0.0+1

environment:
  sdk: '>=2.18.2 <3.0.0'

# Dependencies specify other packages that your package needs in order to work.
# To automatically upgrade your package dependencies to the latest versions
# consider running `flutter pub upgrade --major-versions`. Alternatively,
# dependencies can be manually updated by changing the version numbers below to
# the latest version available on pub.dev. To see which dependencies have newer
# versions available, run `flutter pub outdated`.
dependencies:
  flutter:
    sdk: flutter


  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.2
  google_fonts: ^6.2.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  # The "flutter_lints" package below contains a set of recommended lints to
  # encourage good coding practices. The lint set provided by the package is
  # activated in the `analysis_options.yaml` file located at the root of your
  # package. See that file for information about deactivating specific lint
  # rules and activating additional ones.
  flutter_lints: ^3.0.1

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter packages.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg
  assets:
    - assets/page-1/images/rectangle.png
    - assets/page-1/images/group.png
    - assets/page-1/images/ui-icon.png
    - assets/page-1/images/placeholder-icon.png
    - assets/page-1/images/back.png
    - assets/page-1/images/wifi.png
    - assets/page-1/images/proggression-bar.png
    - assets/page-1/images/wifi-6JK.png
    - assets/page-1/images/ellipse-409.png
    - assets/page-1/images/search.png
    - assets/page-1/images/interface-settings.png
    - assets/page-1/images/ui-icon-J2b.png
    - assets/page-1/images/battery.png
    - assets/page-1/images/auto-group-rqn7.png
    - assets/page-1/images/left-side.png
    - assets/page-1/images/icn-resize-icn-md.png
    - assets/page-1/images/icon.png
    - assets/page-1/images/left-side-LzT.png
    - assets/page-1/images/ui-icon-NCF.png
    - assets/page-1/images/auto-group-pttp.png
    - assets/page-1/images/icon-more.png
    - assets/page-1/images/wifi-ZnP.png
    - assets/page-1/images/vector.png
    - assets/page-1/images/group-8j1.png
    - assets/page-1/images/keyboardarrowup.png
    - assets/page-1/images/keyboardarrowup-LAB.png
    - assets/page-1/images/status-bar.png
    - assets/page-1/images/group-mkb.png
    - assets/page-1/images/wifi-kVM.png
    - assets/page-1/images/back-TEf.png
    - assets/page-1/images/bell-ringing.png
    - assets/page-1/images/puzzlepiece.png
    - assets/page-1/images/vector-TLs.png
    - assets/page-1/images/cellular-connection.png
    - assets/page-1/images/ui-icon-eCf.png
    - assets/page-1/images/ui-icon-j5h.png
    - assets/page-1/images/rectangle-ZDh.png
    - assets/page-1/images/ui-icon-Cy5.png
    - assets/page-1/images/group-21.png
    - assets/page-1/images/vector-q8b.png
    - assets/page-1/images/battery-wHR.png
    - assets/page-1/images/auto-group-jclf.png
    - assets/page-1/images/group-Qgf.png
    - assets/page-1/images/puzzlepiece-87R.png
    - assets/page-1/images/left-side-VMR.png
    - assets/page-1/images/group-127403.png
    - assets/page-1/images/auto-group-6r9m.png
    - assets/page-1/images/battery-o7M.png
    - assets/page-1/images/battery-c7y.png
    - assets/page-1/images/left-side-w6w.png
    - assets/page-1/images/mask-group.png
    - assets/page-1/images/cellular-connection-F5y.png
    - assets/page-1/images/ui-icon-nbh.png
    - assets/page-1/images/battery-J4F.png
    - assets/page-1/images/ui-icon-r5m.png
    - assets/page-1/images/group-16.png
    - assets/page-1/images/search-xPh.png
    - assets/page-1/images/cellular-connection-dkj.png
    - assets/page-1/images/puzzlepiece-tyu.png
    - assets/page-1/images/left-side-dRh.png
    - assets/page-1/images/wifi-By1.png
    - assets/page-1/images/puzzlepiece-qXm.png
    - assets/page-1/images/cellular-connection-nT1.png
    - assets/page-1/images/group-JAT.png
    - assets/page-1/images/checkbox.png
    - assets/page-1/images/ellipse-10.png
    - assets/page-1/images/wifi-VaF.png
    - assets/page-1/images/auto-group-bsks.png
    - assets/page-1/images/icon-eye.png
    - assets/page-1/images/mask-group-eST.png
    - assets/page-1/images/fov-clipping-plane.png
    - assets/page-1/images/group-21-d5y.png
    - assets/page-1/images/cellular-connection-uS7.png
    - assets/page-1/images/wifi-GGf.png
    - assets/page-1/images/icon-eye-Asq.png
    - assets/page-1/images/battery-WeB.png
    - assets/page-1/images/wifi-4Qo.png
    - assets/page-1/images/auto-group-b66s.png
    - assets/page-1/images/auto-group-ybfm.png
    - assets/page-1/images/checkbox-xFH.png
    - assets/page-1/images/icon-delete-outline.png
    - assets/page-1/images/auto-group-wtq3.png
    - assets/page-1/images/battery-rrT.png
    - assets/page-1/images/group-7Km.png
    - assets/page-1/images/auto-group-sy8f.png
    - assets/page-1/images/interface-settings-VLj.png
    - assets/page-1/images/brain-1-bg.png
    - assets/page-1/images/ellipse-2.png
    - assets/page-1/images/img7084-1.png
    - assets/page-1/images/auto-group-svnt.png
    - assets/page-1/images/icon-left.png
    - assets/page-1/images/placeholder-icon-v1M.png
    - assets/page-1/images/icon-eye-7Xd.png
    - assets/page-1/images/wifi-BH9.png
    - assets/page-1/images/na.png
    - assets/page-1/images/left-side-4jq.png
    - assets/page-1/images/applelogoblack-1.png
    - assets/page-1/images/vector-6rj.png
    - assets/page-1/images/battery-FUj.png
    - assets/page-1/images/frame-9.png
    - assets/page-1/images/icon-eye-3FV.png
    - assets/page-1/images/group-CPH.png
    - assets/page-1/images/battery-3Gb.png
    - assets/page-1/images/na-Z7m.png
    - assets/page-1/images/cellular-connection-bkb.png
    - assets/page-1/images/battery-hUB.png
    - assets/page-1/images/cellular-connection-pUF.png
    - assets/page-1/images/cellular-connection-y2w.png
    - assets/page-1/images/nbcharts-linechats.png
    - assets/page-1/images/ellipse-21.png
    - assets/page-1/images/group-JTh.png
    - assets/page-1/images/wifi-dF5.png
    - assets/page-1/images/vector-mkT.png
    - assets/page-1/images/wifi-Y3h.png
    - assets/page-1/images/cellular-connection-TgT.png
    - assets/page-1/images/group-16-7Qj.png
    - assets/page-1/images/auto-group-vjak.png
    - assets/page-1/images/back-WSs.png
    - assets/page-1/images/ellipse-20.png
    - assets/page-1/images/oval.png
    - assets/page-1/images/img7084-1-1u9.png
    - assets/page-1/images/intersect.png
    - assets/page-1/images/auto-group-5kjm.png
    - assets/page-1/images/user-image.png
    - assets/page-1/images/wifi-gzb.png
    - assets/page-1/images/battery-qsV.png
    - assets/page-1/images/mask-group-bLs.png
    - assets/page-1/images/iphone-x-status-bars-status-bar-black.png
    - assets/page-1/images/profile.png
    - assets/page-1/images/auto-group-gxaf.png
    - assets/page-1/images/battery-jQT.png
    - assets/page-1/images/calendar.png
    - assets/page-1/images/battery-4nj.png
    - assets/page-1/images/keyboardarrowup-zgP.png
    - assets/page-1/images/keyboardarrowup-9pB.png
    - assets/page-1/images/oval-MKM.png
    - assets/page-1/images/healthicons-ui-menu-negative.png
    - assets/page-1/images/vector-4.png
    - assets/page-1/images/fill-1.png
    - assets/page-1/images/battery-pMm.png
    - assets/page-1/images/battery-uNw.png
    - assets/page-1/images/applelogoblack-1-AJj.png
    - assets/page-1/images/group-16-r71.png
    - assets/page-1/images/left-side-jrF.png
    - assets/page-1/images/information.png
    - assets/page-1/images/background-bg.png
    - assets/page-1/images/bxs-search.png
    - assets/page-1/images/wifi-AQF.png
    - assets/page-1/images/background-bg-H5R.png
    - assets/page-1/images/fill-4.png
    - assets/page-1/images/wifi-Pg3.png
    - assets/page-1/images/background-bg-84o.png
    - assets/page-1/images/auto-group-7kjs.png
    - assets/page-1/images/icon-eye-vwh.png
    - assets/page-1/images/fluent-home-16-regular.png
    - assets/page-1/images/group-132.png
    - assets/page-1/images/shape.png
    - assets/page-1/images/image-30.png
    - assets/page-1/images/wifi-aa3.png
    - assets/page-1/images/background-bg-tVm.png
    - assets/page-1/images/verified.png
    - assets/page-1/images/exit.png
    - assets/page-1/images/icon-eye-Hsm.png
    - assets/page-1/images/rectangle-18794.png
    - assets/page-1/images/auto-group-kijb.png
    - assets/page-1/images/notification.png
    - assets/page-1/images/user.png
    - assets/page-1/images/brightness.png
    - assets/page-1/images/credit-card.png
    - assets/page-1/images/mdi-account-outline.png
    - assets/page-1/images/img7090-1.png

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
